### ISSUE TITLE
Workaround for package loading + install 

### ISSUE THREAD

**Issue by lisancao** [biocswirl-dev-team/BiocSwirl#24]
Currently bioconductor package installs and autoloads is not compatible with swirl's base functionality- we would like a way to resolve this

**Comment by juliaphilipp** [comment]
installing Bioconductor packages in initLesson.R works!

I like to test if the package is installed first, like so:
`if (!requireNamespace("Rsubread", quietly = TRUE))
  BiocManager::install("Rsubread")`

2 important things:
a) the Bioconductor packages that are installed like that, will also have to be loaded in the initLesson.R with` library()` or `require()`
b) the Bioconductor packages that are installed like that, cannot be listed in dependson.txt - I think that file is run first and it will throw an error because the packages aren't installed yet and it will try to install with `install.packages()`
