### ISSUE TITLE
RNA-seq analysis pre-processing lesson

### ISSUE THREAD

**Issue by neuroendokat** [biocswirl-dev-team/BiocSwirl#32]
Hi,

In this lesson I reached the question "Subset the dds object for the rows in "keep". Assign the result to dds again" for which the answer is given as

`dds <- dds[keep,]`

which gives me this error: "Error: subscript is a logical vector with out-of-bounds TRUE values."

The previous questions seem to have been right to get me to this point, and after looking at "keep" and "dds" in my environment it looks like they are what they should be (keep is a logical vector for each gene, and dds is a DESeqDataSet).

Any advice would be greatly appreciated! Thanks.

**Comment by juliaphilipp** [comment]
Hi Kat,
thanks for reaching out!

I am getting this type of error, if I execute the `dds <- dds[keep,]` command twice. So essentially trying to subset the already subsetted dds object. The error then occurs because the 'keep' vector contains information that doesn't correspond to anything in dds anymore since it was already filtered.

If this problem prevents you from finishing the lesson, there are two solutions you could try:
a) restart that lesson, that will ensure the dds object is back to its prefiltered, full size
b) enter the 'play mode' with `swirl::play()`, then execute the following to restore the original dds (a command you executed earlier in the lesson): `dds <- DESeqDataSetFromMatrix(dataset, colData, design= ~ condition)`, exit the play mode with `swirl::nxt()` and try `dds <- dds[keep,]` again.

Please let me know if this was helpful or if the problem persists. I can see now that reusing these variable names might not be the best way to go.

Cheers!

**Comment by lisancao** [comment]
Hey Kat, 

Hopefully this fixed your issue. I am marking this as closed now, feel free to reopen it if the solutions didn't work.

**Comment by neuroendokat** [comment]
Yup, it did. Thanks for all your help!
